### ISSUE TITLE
thread_operators.hpp misses include of "../util_type.hpp"

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/hipCUB#11]
https://github.com/ROCmSoftwarePlatform/hipCUB/blob/master/hipcub/include/hipcub/rocprim/thread/thread_operators.hpp

WIthout     said include, KeyValuePair is not defined and PyTorch compilation crashes.

**Comment by ex-rzr** [comment]
How do you include hipCUB headers? I hope not `hipcub/rocprim/thread/thread_operators.hpp`?

The valid way to include the main header only:
```cpp
#include <hipcub/hipcub.hpp>
```

The reason is to support both CUB and rocPRIM, otherwise the user would need to deal with paths.

**Comment by saadrahim** [comment]
Please add this to README. Also where should one define the HIPCUB_ARCH=1. Is that auto detected by compiler?

**Comment by ex-rzr** [comment]
Nowhere.
If you include the main header, this definition will be set:
https://github.com/ROCmSoftwarePlatform/hipCUB/blob/b45cc0ccac683208457b14b1776c929e33cfae64/hipcub/include/hipcub/cub/hipcub.hpp#L36
https://github.com/ROCmSoftwarePlatform/hipCUB/blob/b6ce7dbe9c376b869642203c42d17a0eed975971/hipcub/include/hipcub/rocprim/util_ptx.hpp#L39

**Comment by saadrahim** [comment]
This needs to be in the documentation.

**Comment by ex-rzr** [comment]
Ah, I remember that the notice about the main header was somewhere.
It's here:
https://github.com/ROCmSoftwarePlatform/hipCUB/blob/master/doc/mainpage.dox#L16

I'll add this info to README.

**Comment by saadrahim** [comment]
However, a comment from the users:

> PyTorch is including certain cub headers directly (device_scan, device_reduce, block_reduce, …) – we expect hipCUB to be compatible to that use case.

**Comment by ex-rzr** [comment]
We can't do this, because hipCUB is supposed to support two backends.

**Comment by ex-rzr** [comment]
Fixed in https://github.com/ROCmSoftwarePlatform/hipCUB/pull/14
