### ISSUE TITLE
How to porting cub::BaseTraits in ROCM platform

### ISSUE THREAD

**Issue by qili93** [ROCmSoftwarePlatform/hipCUB#116]
Hi There,

I'm working on poring a deep learning framework from CUDA to HIP, and facing some codes with no idea how to change it from CUDA to HIP? Would you please kindly help to support? Thanks in advance :)

```c++
// set cub base traits in order to handle float16
namespace cub {
template <>
struct NumericTraits<paddle::platform::float16>
    : BaseTraits<FLOATING_POINT, true, false, uint16_t,
                 paddle::platform::float16> {};
}  // namespace cub
```

I changed the above lines of code to the following lines, while compile errors thrown as hipCUB is actually a wrapper of rocPRIM on HIP platform.

```c++
// set cub base traits in order to handle float16
namespace hipcub {
template <>
struct NumericTraits<paddle::platform::float16>
    : BaseTraits<FLOATING_POINT, true, false, uint16_t,
                 paddle::platform::float16> {};
}  // namespace cub
```

**Comment by xuhuisheng** [comment]
@qili93 Did you try hipify-perl to convert cuda to hip automaticly?

**Comment by qili93** [comment]
@xuhuisheng The above code cannot convert simply by hipify-perl tool.

Resolve this issue by change the above code to the following code, then rocprim can also handle an unknown type "paddle::platform::float16" as uint16_t. Close this issue, and thanks all the same.

```c++
namespace rocprim {
namespace detail {
template<>
struct radix_key_codec_base<paddle::platform::float16> 
     : radix_key_codec_integral<paddle::platform::float16, uint16_t> {};
} // namespace detail
} // namespace rocprim
```
