### ISSUE TITLE
exclusive scan not callable from device/device_scan.hpp

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/hipCUB#12]
Error during PyTorch compilation:
/opt/rocm/hipcub/include/hipcub/rocprim/device/device_scan.hpp:113:16: note: must qualify identifier to find this declaration in dependent base class
    hipError_t ExclusiveScan(void *d_temp_storage,
               ^
/opt/rocm/hipcub/include/hipcub/rocprim/device/device_scan.hpp:99:16: error: no matching function for call to 'ExclusiveScan'
        return ExclusiveScan(
               ^~~~~~~~~~~~~
/opt/rocm/hipcub/include/hipcub/rocprim/device/device_scan.hpp:113:16: note: candidate function template not viable: no known conversion from '::hipcub::Sum' to 'int' for 7
th argument
    hipError_t ExclusiveScan(void *d_temp_storage,
               ^
/opt/rocm/hipcub/include/hipcub/rocprim/device/device_scan.hpp:99:16: error: no matching function for call to 'ExclusiveScan'
        return ExclusiveScan(
               ^~~~~~~~~~~~~
/opt/rocm/hipcub/include/hipcub/rocprim/device/device_scan.hpp:113:16: note: candidate function template not viable: no known conversion from '::hipcub::Sum' to 'int' for 7
th argument
    hipError_t ExclusiveScan(void *d_temp_storage,
 
Type error

**Comment by ex-rzr** [comment]
Fixed in #13
