### ISSUE TITLE
CuPy Issue reported to hip

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/hipCUB#129]
https://github.com/ROCm-Developer-Tools/HIP/issues/2247

**Comment by saadrahim** [comment]
We should see if this issue requires coverage in hipcub.

**Comment by neon60** [comment]
@saadrahim Can we close this?

**Comment by leofang** [comment]
The specific compiler issue was fixed in ROCm 4.2.0. Not sure if you are interested in other aspects or not.

**Comment by doctorcolinsmith** [comment]
Closed as reported fixed in 4.2.0
