### ISSUE TITLE
Cmake issues for hipCUB

### ISSUE THREAD

**Issue by saadrahim** [ROCmSoftwarePlatform/hipCUB#19]
/opt/rocm/hipcub/lib/cmake/hipcub/hipcub-config.cmake contains:
set(hipcub_LIBRARIES hipcub-targets)
set(hipcub_LIBRARY hipcub-targets)
set(HIPCUB_LIBRARIES hipcub-targets)
set(HIPCUB_LIBRARY hipcub-targets)
set(hipcub_LIBRARIES hipcub-targets)
set(hipcub_LIBRARY hipcub-targets)
 
There is no hipcub-targets library and using the cmake config causes PyTorch compilation to fail. These sets need to be removed.

Saad: I think these issues are related to rocm-cmake. This might need a patch for that project.

**Comment by ex-rzr** [comment]
We have a fix here: https://github.com/ROCmSoftwarePlatform/hipCUB/commits/develop_stream_20190531

Could you check this branch before merging?

**Comment by saadrahim** [comment]
I looked at this branch and it looks good. Can you do the same for rocprim and rocthrust? They are also header only libraries that do not need library targets.

**Comment by ex-rzr** [comment]
Yes, the fix for rocPRIM is ready, for rocThrust is on the way, I'll create PRs for all 3 projects.
