### ISSUE TITLE
backend/rocprim/hipcub.hpp does not include device/device_partition.hpp

### ISSUE THREAD

**Issue by xinyazhang** [ROCmSoftwarePlatform/hipCUB#202]
This creates incompatibility with CUB.
When the code references `cub::DevicePartition` and only includes `cub.cuh`, it compiles with CUB but not hipCUB.

In this case, the code also cannot be hipified and human intervention is needed.

**Comment by MKKnorr** [comment]
Thank you for the information, the hipCUB-team is currently working on this issue.

**Comment by doctorcolinsmith** [comment]
Fix was merged as part of another PR and should be available now.
