### ISSUE TITLE
allow including headers only with NVCC in cmake projects

### ISSUE THREAD

**Issue by jglaser** [ROCmSoftwarePlatform/hipCUB#56]
How should hipCUB be used as a subproject inside a cmake project? We would like to include it in HOOMD for the case where a system wide install is not available and compilation is done through nvcc directly (no hipcc). The only thing that's holding us back is that `hipCUB/hipcub/include/hipcub/hipcub_version.hpp` does not exist and needs to be generated by the CMake system. Since for nvcc, hipcub does not depend on rocPRIM and is therefore header-only, I think the easiest solution would be to not include that file on when `__HIP_PLATFORM_NVCC__` is defined. Would that be acceptable to the developers?

Otherwise, we would have include hipCUB's cmake logic into ours via `add_subdirectory`. However, currently it looks like hipCUB's cmake does it's own testing of the CUDA compiler and also pulls in additional dependencies (google test), which seems like an undesirable complication.

**Comment by saadrahim** [comment]
Thanks for your feedback and PR. I will approve soon.

**Comment by saadrahim** [comment]
@neon60 What is your opinion on this? I think we should fix our hipcub cmake files to not pull in google test unless explicitly required.

**Comment by neon60** [comment]
> @neon60 What is your opinion on this? I think we should fix our hipcub cmake files to not pull in google test unless explicitly required.

If we set the cmake BUILD_TEST option to OFF, the cmake will not add the google test as dependency:

https://github.com/ROCmSoftwarePlatform/hipCUB/blob/490b93d1ec189d4fcc0255ab29e6465b8798182b/cmake/Dependencies.cmake#L91

We can set the default option to OFF, if you want.

**Comment by neon60** [comment]
Hello @jglaser 

You can avoid the `add_subdirectory` if you use `download_project` instead, which will download the hipCUB to the build folder.

The hipCUB integration code should be like this at that case:
```
# Download hipCUB (only for ROCm platform)
if(NOT DEFINED HIPCUB_ROOT)
  message(STATUS "Downloading and building hipCUB.")
  set(HIPCUB_ROOT "${CMAKE_CURRENT_BINARY_DIR}/rocprim" CACHE PATH "")
  download_project(
    PROJ                hipcub
    GIT_REPOSITORY      https://github.com/ROCmSoftwarePlatform/hipCUB.git
    GIT_TAG             master
    INSTALL_DIR         ${HIPCUB_ROOT}
    CMAKE_ARGS          -DBUILD_TEST=OFF -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
    LOG_DOWNLOAD        TRUE
    LOG_CONFIGURE       TRUE
    LOG_BUILD           TRUE
    LOG_INSTALL         TRUE
    BUILD_PROJECT       TRUE
    UPDATE_DISCONNECTED TRUE
  )
endif()
find_package(rocprim REQUIRED CONFIG PATHS "${HIPCUB_ROOT}")
```
If you call the cmake with the following argumentum -DBUILD_TEST=OFF, you can avoid the google test as additional dependencies too.

The hipCUB version number should be available for both backend (nvcc too), that's why we should not move the version include.

**Comment by jglaser** [comment]
Hi thanks for the heads-up and sorry for the late follow-up.

We are currently putting in place another abstraction layer in HOOMD between the C++ code and HIP/CUDA, and will evaluate how we can then make hipCUB an external dependency.

https://github.com/mphoward/neighbor/pull/11

**Comment by saadrahim** [comment]
I will close this issue for now. Please feel free to open it again when if you need further assistance.
