### ISSUE TITLE
set HIP_PLATFORM=nvcc for nvidai GPU, cmake error  

### ISSUE THREAD

**Issue by yaomingamd** [ROCmSoftwarePlatform/hipCUB#76]
[alice@prj47-rack-96 build]$ CXX=hipcc cmake -DBUILD_TEST ..
Parse error in command line argument: -DBUILD_TEST
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

[alice@prj47-rack-96 build]$ CXX=hipcc cmake -DBUILD_TEST=ON ..
CMake Warning (dev) at CMakeLists.txt:44 (set):
  implicitly converting 'BOOLEAN' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CUB will be used as hipCUB's backend.
-- Downloading and building GTest.
-- Downloading/updating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alice/test/hipCUB/build/googletest-download
Scanning dependencies of target googletest-download
[ 11%] Skipping update step for 'googletest-download'
[ 22%] Performing configure step for 'googletest-download'
CMake Error at /home/alice/test/hipCUB/build/googletest-download/googletest-download-prefix/src/googletest-download-stamp/googletest-download-configure-.cmake:49 (message):
  Command failed: 1

   '/home/alice/cern/nvidia-test/alice/sw/slc7_x86-64/CMake/v3.15.3-1/bin/cmake' '-DBUILD_GTEST=ON' '-DINSTALL_GTEST=ON' '-Dgtest_force_shared_crt=ON' '-DBUILD_SHARED_LIBS=ON' '-DCMAKE_INSTALL_PREFIX=/home/alice/test/hipCUB/build/gtest' '-GUnix Makefiles' '/home/alice/test/hipCUB/build/googletest-src'

  See also

    /home/alice/test/hipCUB/build/googletest-download/googletest-download-prefix/src/googletest-download-stamp/googletest-download-configure-*.log

gmake[2]: *** [googletest-download-prefix/src/googletest-download-stamp/googletest-download-configure] Error 1
gmake[1]: *** [CMakeFiles/googletest-download.dir/all] Error 2
gmake: *** [all] Error 2
CMake Error at cmake/DownloadProject.cmake:168 (message):
  Build step for googletest failed: 2
Call Stack (most recent call first):
  cmake/Dependencies.cmake:95 (download_project)
  CMakeLists.txt:59 (include)

-- Configuring incomplete, errors occurred!
See also "/home/alice/test/hipCUB/build/CMakeFiles/CMakeOutput.log".
See also "/home/alice/test/hipCUB/build/CMakeFiles/CMakeError.log".

**Comment by saadrahim** [comment]
The NVIDIA build instructions have been updated in the README.md file. Please refer to that and try again.

**Comment by saadrahim** [comment]
Closing as this issue is old. Please reopen if required.
